dist: bionic
language: python
python: 3.9

install:
  - pip install flake8 flake8_polyfill kodi-addon-checker

before_script:
- git config core.quotepath false

# command to run our tests
script:
  - flake8 ./ --statistics --show-source --ignore=E501  # check python structure against flake8 tests, ignore long lines
  - kodi-addon-checker --branch=matrix
